apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  affinity:
    podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
matchExpressions:
  - key: security
operator: In
values:
  - S1
topologyKey: failure-domain.beta.kubernetes.io/zone
containers:
  - name: ubuntu-pod
image: ubuntu

