apiVersion: v1
kind: Pod
metadata: null
name: secret-vol-pod
spec: null
volumes:
  - name: secret-volume
secret: null
secretName: test-secret
containers:
  - name: test-container
image: 'alpine:latest'
command:
  - sleep
  - '9999'
volumeMounts:
  - name: secret-volume
mountPath: /etc/secret-volume
